PR_12
OksanaEfanova/test pull request #12
Opened 2017-05-24 13:45 UTC by TestGitHub100500

PR_12

2017-05-24 14:02 UTC, TestGitHub100500 commented
change

2017-05-25 12:15 UTC, OksanaEfanova commented
comment

2017-05-25 12:23 UTC, OksanaEfanova commented
comment7

2017-05-25 12:30 UTC, OksanaEfanova commented
comment9

2017-05-25 12:57 UTC, OksanaEfanova commented
comment 13

2017-05-25 13:54 UTC, OksanaEfanova commented
comment 14

2017-05-25 14:07 UTC, OksanaEfanova commented
comment 15

2017-05-25 14:35 UTC, OksanaEfanova commented
comment 16

2017-05-25 15:15 UTC, OksanaEfanova commented
comment 17

2017-05-25 15:39 UTC, OksanaEfanova commented
comment 18

2017-05-26 10:10 UTC, OksanaEfanova reviewed
improve something

2017-05-26 10:13 UTC, TestGitHub100500 reviewed
fix

2017-05-26 10:35 UTC, OksanaEfanova requested changes
add1

2017-05-26 10:38 UTC, TestGitHub100500 reviewed
fix2

2017-05-26 10:40 UTC, OksanaEfanova approved these changes

2017-05-30 12:57 UTC, OksanaEfanova requested changes

2017-05-30 12:57 UTC, OksanaEfanova commented on PR_11
> +PR_11
MOVE

2017-06-14 08:58 UTC, OksanaEfanova requested changes
change

2017-06-14 10:33 UTC, OksanaEfanova commented
123

2017-06-14 10:34 UTC, OksanaEfanova requested changes
testtest

2017-06-14 10:36 UTC, OksanaEfanova commented
dffffggfd

2017-06-14 10:42 UTC, OksanaEfanova commented
test test

2017-06-14 10:48 UTC, OksanaEfanova commented
qwe

2017-06-14 12:04 UTC, OksanaEfanova commented
test

2017-06-15 11:47 UTC, OksanaEfanova commented
testtest

2017-06-15 12:21 UTC, OksanaEfanova commented on PR_11
> +PR_11
1

2017-06-15 12:21 UTC, OksanaEfanova commented
2

2017-06-22 15:37 UTC, OksanaEfanova commented
1

2017-12-25 09:56 UTC, closed without merging