PR_13
OksanaEfanova/test pull request #13
Opened 2017-05-26 10:48 UTC by TestGitHub100500

Create PR_13

2017-05-26 10:52 UTC, OksanaEfanova commented
comment

2017-05-26 10:53 UTC, OksanaEfanova commented
comment

2017-05-26 11:03 UTC, OksanaEfanova reviewed
add review

2017-05-26 16:07 UTC, OksanaEfanova commented on PR_13
> +PR_13
O NOOO!

2017-05-26 16:07 UTC, TestGitHub100500 commented on PR_13
> +PR_13
YES

2017-05-30 12:27 UTC, OksanaEfanova commented on PR_13
> +PR_13
BLa

2017-06-09 15:45 UTC, OksanaEfanova reviewed
Test Rev

2017-06-09 16:05 UTC, OksanaEfanova approved these changes
approve

2017-06-13 13:36 UTC, OksanaEfanova reviewed
123

2017-06-13 15:05 UTC, OksanaEfanova commented
qwewqe

2017-06-13 15:07 UTC, OksanaEfanova commented on PR_13
> +PR_13
12333

2017-06-13 15:19 UTC, OksanaEfanova approved these changes

2017-06-13 15:20 UTC, OksanaEfanova approved these changes
123

2017-06-13 16:07 UTC, OksanaEfanova approved these changes
789

2017-06-13 16:08 UTC, OksanaEfanova approved these changes

2017-06-13 16:08 UTC, OksanaEfanova commented
werwr

2017-06-14 13:29 UTC, OksanaEfanova reviewed
345

2017-06-14 13:31 UTC, OksanaEfanova commented
123

2017-06-14 13:35 UTC, OksanaEfanova commented
123

2017-06-14 13:41 UTC, OksanaEfanova commented
951

2017-06-14 14:21 UTC, OksanaEfanova commented
852

2017-06-14 14:28 UTC, OksanaEfanova reviewed
567

2017-06-14 14:31 UTC, OksanaEfanova commented
qwe

2017-06-14 14:36 UTC, OksanaEfanova requested changes
852

2017-06-14 14:38 UTC, OksanaEfanova approved these changes

2017-06-14 14:40 UTC, OksanaEfanova commented
456

2017-06-14 14:40 UTC, OksanaEfanova reviewed
werwrwr

2017-06-14 14:54 UTC, OksanaEfanova commented
ijn

2017-06-14 15:04 UTC, OksanaEfanova commented
okm

2017-06-15 08:36 UTC, OksanaEfanova commented
123

2017-06-15 11:18 UTC, OksanaEfanova commented
qwe

2017-06-20 11:03 UTC, OksanaEfanova approved these changes

2017-06-20 11:05 UTC, OksanaEfanova commented on PR_13
> +PR_13
end

2017-06-20 11:12 UTC, OksanaEfanova commented on PR_13
> +PR_13
end2

2017-06-20 11:24 UTC, OksanaEfanova commented on PR_13
> +PR_13
end3

2017-07-11 15:26 UTC, OksanaEfanova commented on PR_13
> +PR_13
end4

2017-12-25 09:56 UTC, closed without merging