PR_15
OksanaEfanova/test pull request #15
Opened 2017-05-29 12:16 UTC by OksanaEfanova

PR_15

2017-05-29 12:18 UTC, TestGitHub100500 requested changes

2017-05-29 12:18 UTC, TestGitHub100500 commented on PR_15
> +PR_15
12

2017-05-29 12:18 UTC, TestGitHub100500 commented on PR_15
> +PR_15
12

2017-05-30 12:18 UTC, TestGitHub100500 approved these changes

2017-06-07 13:41 UTC, OksanaEfanova commented
sdfsfsf

2017-06-07 15:47 UTC, defanov-da commented
1

2017-06-07 16:03 UTC, OksanaEfanova commented on PR_15
> +PR_15
testtesttest

2017-06-08 07:45 UTC, OksanaEfanova commented
123345

2017-06-08 07:46 UTC, OksanaEfanova commented
789

2017-06-08 07:56 UTC, OksanaEfanova commented
zxc

2017-06-08 08:18 UTC, OksanaEfanova commented
vbn

2017-06-08 08:21 UTC, OksanaEfanova commented
rty

2017-06-08 08:40 UTC, OksanaEfanova commented
678

2017-06-08 08:42 UTC, OksanaEfanova commented
qwe

2017-06-08 08:43 UTC, OksanaEfanova commented
qwe

2017-06-08 09:04 UTC, OksanaEfanova commented
147

2017-06-08 09:31 UTC, OksanaEfanova commented
852

2017-06-08 09:32 UTC, OksanaEfanova commented
852

2017-06-08 09:33 UTC, OksanaEfanova commented
852

2017-06-09 15:09 UTC, OksanaEfanova commented
951

2017-06-09 15:15 UTC, OksanaEfanova commented
741

2017-06-09 15:18 UTC, OksanaEfanova commented
tetet

2017-06-20 10:21 UTC, OksanaEfanova commented
1

2017-06-20 10:47 UTC, OksanaEfanova commented
1

2017-06-20 10:56 UTC, OksanaEfanova commented
1

2017-06-20 11:02 UTC, OksanaEfanova commented
2

2017-12-25 09:56 UTC, closed without merging