Create PR_16
OksanaEfanova/test pull request #16
Opened 2017-06-20 11:29 UTC by OksanaEfanova

desc

2017-07-05 09:09 UTC, TestGitHub100500 commented on PR_16
> +PR_16
somecomment

2017-07-05 09:28 UTC, TestGitHub100500 commented on PR_16
> +PR_16
somecomment2

2017-07-05 09:29 UTC, OksanaEfanova commented on PR_16
> +PR_16
response

2017-07-05 09:29 UTC, OksanaEfanova commented on PR_16
> +PR_16
response2

2017-07-05 09:54 UTC, TestGitHub100500 commented
comment1

2017-07-05 09:54 UTC, TestGitHub100500 commented on PR_16
> +PR_16
somecomment3

2017-07-25 13:15 UTC, OksanaEfanova commented
A+

2017-07-25 15:26 UTC, TestGitHub100500 requested changes
RCH

2017-07-25 15:29 UTC, OksanaEfanova commented
comment

2017-07-25 15:32 UTC, TestGitHub100500 requested changes
RCH2

2017-07-25 15:33 UTC, OksanaEfanova commented
comment

2017-12-25 09:56 UTC, closed without merging