Create PR_17
OksanaEfanova/test pull request #18
Opened 2017-07-07 12:45 UTC by TestGitHub100500

PR_17

2017-07-11 15:27 UTC, OksanaEfanova commented
comment

2017-07-19 10:15 UTC, OksanaEfanova requested changes

2017-07-19 10:15 UTC, OksanaEfanova commented on PR_17
> +
commet1

2017-07-19 10:16 UTC, TestGitHub100500 commented on PR_17
> +
commet2

2017-07-19 10:18 UTC, OksanaEfanova commented on PR_17
> +
commet2

2017-12-25 09:56 UTC, closed without merging