Create tyutu
OksanaEfanova/test pull request #4
Opened 2017-05-03 16:50 UTC by OksanaEfanova

2017-05-04 10:12 UTC, TestGitHub100500 commented
test

2017-05-04 10:13 UTC, TestGitHub100500 reviewed
qwee

2017-05-30 12:26 UTC, TestGitHub100500 commented on tyutu
> +add some code
ЩЩЩ

2017-07-20 10:25 UTC, TestGitHub100500 commented on tyutu
> +add some code
123

2017-07-20 10:26 UTC, TestGitHub100500 reviewed
comment

2017-07-20 10:26 UTC, TestGitHub100500 requested changes

2017-07-20 10:26 UTC, TestGitHub100500 commented on tyutu
> +tyutyu
1

2017-07-20 10:27 UTC, OksanaEfanova commented on tyutu
> +tyutyu
2

2017-07-20 10:27 UTC, TestGitHub100500 approved these changes

2017-07-20 10:49 UTC, OksanaEfanova reviewed
8

2017-07-20 10:49 UTC, OksanaEfanova commented on tyutu
> +tyutyu
3

2017-12-25 09:56 UTC, closed without merging