Create test100500_for slack
OksanaEfanova/test pull request #7
Opened 2017-05-04 12:42 UTC by OksanaEfanova

2017-05-04 13:13 UTC, TestGitHub100500 requested changes
456

2017-05-04 13:14 UTC, TestGitHub100500 approved these changes

2017-05-04 13:16 UTC, TestGitHub100500 submitted a review, later dismissed

2017-05-25 10:04 UTC, TestGitHub100500 requested changes
daaa

2017-05-25 12:30 UTC, OksanaEfanova commented
comment12

2017-05-25 12:57 UTC, OksanaEfanova commented
comment13

2017-05-26 10:05 UTC, TestGitHub100500 approved these changes

2017-05-26 10:06 UTC, TestGitHub100500 requested changes
NOO

2017-07-20 10:56 UTC, TestGitHub100500 requested changes

2017-07-20 10:56 UTC, TestGitHub100500 commented on test100500_for slack
> +test100500_for slack
comment

2017-12-25 09:56 UTC, closed without merging